package com.github.sistemas_tecnm_uruapan.helpers.utility;



import com.github.sistemas_tecnm_uruapan.helpers.models.Alumno;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.regex.Pattern;

public class StringHelper
{

    public static String obtenerFecha() {
        Calendar c = Calendar.getInstance();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String formattedDate = df.format(c.getTime());
        return formattedDate;
    }
    public boolean isPhone(String val)
    {
        String EXREGTEL="\\d{10}";
        return Pattern.matches(EXREGTEL,val);
    }
    public boolean isCtrolNumber(String val)
    {
        String EXREGTEL="\\d{8}";
        return Pattern.matches(EXREGTEL,val);
    }

    public ArrayList<Alumno> getData()
    {
        ArrayList<Alumno> alumnos = new ArrayList<>();

        alumnos.add(new Alumno ("21040005","ING. EN SISTEMAS COMPUTACIONALES","AGUILAR VEGA JOSE ANTONIO",""));
        alumnos.add(new Alumno ("21040006","ING. EN ADMINISTRACION","AGUILAR DIAZ JUAN DIEGO",""));
        alumnos.add(new Alumno ("21040007","ING. CIVIL","AGUILAR ORTIZ FARES LEONARDO",""));
        alumnos.add(new Alumno ("21040008","ING. EN ADMINISTRACION","ALVAREZ REYES KARLA JATZIRI",""));
        alumnos.add(new Alumno ("21040009","ING. ELECTRONICA","ALMAZO GURROLA JESUS RICARDO",""));
        alumnos.add(new Alumno ("21040010","ING. EN SISTEMAS COMPUTACIONALES","AYALA MIRANDA BRAYAN BERNABE",""));
        alumnos.add(new Alumno ("21040011","ING. ELECTRONICA","ARGOTE REYES FATIMA BERENICE",""));
        alumnos.add(new Alumno ("21040012","ING. EN SISTEMAS COMPUTACIONALES","ARRIAGA CORIA JOSE LUIS",""));
        alumnos.add(new Alumno ("21040013","ING. EN SISTEMAS COMPUTACIONALES","AGUILAR SOSA LUIS",""));
        alumnos.add(new Alumno ("21040014","ING. EN INDUSTRIAS ALIMENTARIAS","ANGUIANO ROMERO CLARA ESTEFANIA",""));
        alumnos.add(new Alumno ("21040015","ING. CIVIL","AGUILAR LOPEZ LUIS DANIEL",""));
        alumnos.add(new Alumno ("21040016","ING. ELECTRONICA","AVILA GARIBAY DAVID ALEJANDRO",""));
        alumnos.add(new Alumno ("21040017","ING. MECANICA","ALARCON PATIÑO SHARON MONSERRAT",""));
        alumnos.add(new Alumno ("21040018","ING. ELECTRONICA","AGUILAR PEREZ MIGUEL ALEJANDRO",""));
        alumnos.add(new Alumno ("21040019","ING. EN ADMINISTRACION","AGUILAR ANGUIANO JOSEFINA SHIOMARA",""));
        alumnos.add(new Alumno ("21040020","ING. CIVIL","AYALA HERNANDEZ EDUARDO",""));
        alumnos.add(new Alumno ("21040021","ING. EN SISTEMAS COMPUTACIONALES","ALMANZA DIAZ JONATHAN",""));
        alumnos.add(new Alumno ("21040022","ING. MECATRONICA","ALFARO RAMIREZ DYLAN FERNANDO",""));
        alumnos.add(new Alumno ("21040023","ING. MECATRONICA","CRUZ QUINTERO OMAR SAMUEL",""));
        alumnos.add(new Alumno ("21040024","ING. EN SISTEMAS COMPUTACIONALES","BECERRA BONILLA GERSON OSIRIS",""));
        alumnos.add(new Alumno ("21040025","ING. MECATRONICA","ACEVEDO MEDINA MARIO",""));
        alumnos.add(new Alumno ("21040026","ING. EN SISTEMAS COMPUTACIONALES","ALVAREZ VARGAS ALEJANDRO",""));
        alumnos.add(new Alumno ("21040027","ING. EN ADMINISTRACION","MENDOZA ESQUIVEL JUDITH",""));
        alumnos.add(new Alumno ("21040028","ING. EN SISTEMAS COMPUTACIONALES","ARELLANO GARCIA ROGELIO FABRIZIO",""));
        alumnos.add(new Alumno ("21040029","ING. EN SISTEMAS COMPUTACIONALES","ALBES VARGAS ALAN",""));
        alumnos.add(new Alumno ("21040030","ING. EN ADMINISTRACION","BEDOLLA MAGAÑA MAYDA VIANEY",""));
        alumnos.add(new Alumno ("21040031","ING. EN ADMINISTRACION","BELMONTES PRECIADO JORGE FERNANDO",""));
        alumnos.add(new Alumno ("21040032","ING. CIVIL","ALCARAZ CALLEJA SAUL JOSAFAT",""));
        alumnos.add(new Alumno ("21040033","ING. EN INDUSTRIAS ALIMENTARIAS","AVILA NAVARRETE JAZMIN ISABEL",""));
        alumnos.add(new Alumno ("21040034","ING. EN SISTEMAS COMPUTACIONALES","ALCALA ACEVES ALEXANDER",""));
        alumnos.add(new Alumno ("21040035","ING. MECANICA","CHAVEZ VALENCIA LUIS DANIEL",""));
        alumnos.add(new Alumno ("21040036","ING. EN ADMINISTRACION","BARRERA CHAVEZ EDER BARUCH",""));
        alumnos.add(new Alumno ("21040037","ING. EN ADMINISTRACION","AISPURO RIOS ITZEL",""));
        alumnos.add(new Alumno ("21040038","ING. EN SISTEMAS COMPUTACIONALES","ARREOLA CASARES JESUS ALEXIS",""));
        alumnos.add(new Alumno ("21040039","ING. MECANICA","NAVARRO LOPEZ SAMUEL",""));
        alumnos.add(new Alumno ("21040040","ING. ELECTRONICA","CALDERON SANCHEZ JUAN CARLOS",""));
        alumnos.add(new Alumno ("21040041","ING. EN ADMINISTRACION","SANCHEZ MURILLO DANIELA CITLALI",""));
        alumnos.add(new Alumno ("21040042","ING. CIVIL","BALTAZAR LOPEZ JONATHAN DAVID",""));
        alumnos.add(new Alumno ("21040043","ING. EN SISTEMAS COMPUTACIONALES","BARRAGAN GARCIA JORGE",""));
        alumnos.add(new Alumno ("21040044","ING. EN SISTEMAS COMPUTACIONALES","AGUILAR JOSHUA KALIL",""));
        alumnos.add(new Alumno ("21040045","ING. EN ADMINISTRACION","CERVANTES LOPEZ RAUL",""));
        alumnos.add(new Alumno ("21040046","ING. EN INDUSTRIAS ALIMENTARIAS","BARRIGA MORALES MARIA FERNANDA",""));
        alumnos.add(new Alumno ("21040047","ING. CIVIL","BUSTOS ESQUIVEL FRIDA MARIANA",""));
        alumnos.add(new Alumno ("21040048","ING. EN SISTEMAS COMPUTACIONALES","CAMACHO ZUÑIGA ALAN JAIR",""));
        alumnos.add(new Alumno ("21040049","ING. INDUSTRIAL","BENJUME ESTRADA CITLALI",""));
        alumnos.add(new Alumno ("21040050","ING. MECATRONICA","CARDENAS GONZALEZ DANIEL",""));
        alumnos.add(new Alumno ("21040051","ING. INDUSTRIAL","CHAVEZ MENDOZA MIGUEL JESUS",""));
        alumnos.add(new Alumno ("21040052","ING. CIVIL","CEDEÑO RODRIGUEZ ERICK",""));
        alumnos.add(new Alumno ("21040053","ING. EN SISTEMAS COMPUTACIONALES","CALZADA MENDOZA AARON",""));
        alumnos.add(new Alumno ("21040054","ING. EN SISTEMAS COMPUTACIONALES","CEJA HERNANDEZ ANDONI",""));
        alumnos.add(new Alumno ("21040055","ING. ELECTRONICA","CASTILLO CASILLAS VICTOR MANUEL",""));
        alumnos.add(new Alumno ("21040056","ING. MECATRONICA","Canela pulido Luis Alberto",""));
        alumnos.add(new Alumno ("21040057","ING. EN ADMINISTRACION","AMBRIZ ESTRADA SALVADOR",""));
        alumnos.add(new Alumno ("21040058","ING. EN ADMINISTRACION","CHAVEZ BEJARANO NATALIA",""));
        alumnos.add(new Alumno ("21040059","ING. INDUSTRIAL","CASAREZ VALENZUELA ANGEL ELOY",""));
        alumnos.add(new Alumno ("21040060","ING. MECATRONICA","CHAPA MORALES ALEJANDRO",""));
        alumnos.add(new Alumno ("21040061","ING. INDUSTRIAL","ARZATE CASTILLO ANGEL RODRIGO",""));
        alumnos.add(new Alumno ("21040062","ING. MECATRONICA","CORONA SORIANO JUAN NORBERTO",""));
        alumnos.add(new Alumno ("21040063","ING. CIVIL","ACOSTA LOPEZ JENNIFER",""));
        alumnos.add(new Alumno ("21040064","ING. MECATRONICA","CAMACHO AGUILA ANGEL ALEXIS",""));
        alumnos.add(new Alumno ("21040065","ING. MECATRONICA","CAPIZ CHAGOLLA JOSE JESUS",""));
        alumnos.add(new Alumno ("21040066","ING. CIVIL","CRISANTO GUERRERO SANTIAGO",""));
        alumnos.add(new Alumno ("21040067","ING. ELECTRONICA","CARRANZA QUINTANA JESUS RAUL",""));
        alumnos.add(new Alumno ("21040068","ING. EN SISTEMAS COMPUTACIONALES","CARDENETE LEGORRETA ALBERTO",""));
        alumnos.add(new Alumno ("21040069","ING. EN SISTEMAS COMPUTACIONALES","CHAVEZ DAVILA JOAQUIN YAHIR",""));
        alumnos.add(new Alumno ("21040070","ING. ELECTRONICA","CERON HERNANDEZ ANGEL IVAN",""));
        alumnos.add(new Alumno ("21040071","ING. MECATRONICA","AMEZCUA HERNANDEZ JESUS IGNACIO",""));
        alumnos.add(new Alumno ("21040072","ING. EN SISTEMAS COMPUTACIONALES","RODRIGUEZ SANCHEZ JEFFREY",""));
        alumnos.add(new Alumno ("21040073","ING. EN SISTEMAS COMPUTACIONALES","CASTAÑEDA GALLEGOS DANIEL ALEJANDRO",""));
        alumnos.add(new Alumno ("21040074","ING. ELECTRONICA","DELGADO GARCIA JUAN FRANCISCO",""));
        alumnos.add(new Alumno ("21040075","ING. INDUSTRIAL","DOMINGUEZ PONCE JULIO CESAR",""));
        alumnos.add(new Alumno ("21040076","ING. EN SISTEMAS COMPUTACIONALES","CALDERON AYALA JAN MISAEL",""));
        alumnos.add(new Alumno ("21040077","ING. EN ADMINISTRACION","CRUZ CAMPOS JENYFER",""));
        alumnos.add(new Alumno ("21040078","ING. EN ADMINISTRACION","CASTILLO ARELLANO LESLY PAOLA",""));
        alumnos.add(new Alumno ("21040079","ING. INDUSTRIAL","FUENTES GARCIA ANGEL JESUS",""));
        alumnos.add(new Alumno ("21040080","ING. INDUSTRIAL","MUÑOZ ALEMAN ESMERALDA",""));
        alumnos.add(new Alumno ("21040081","ING. EN ADMINISTRACION","ALVAREZ MUÑOZ REYNALDA YUNUEN",""));
        alumnos.add(new Alumno ("21040082","ING. MECATRONICA","ECHEVARRIA GUTIERREZ FRANCISCO",""));
        alumnos.add(new Alumno ("21040083","ING. EN SISTEMAS COMPUTACIONALES","FERNANDEZ RANGEL GERARDO",""));
        alumnos.add(new Alumno ("21040084","ING. CIVIL","ESCOBEDO SILVA CRISTIAN HASSIEL",""));
        alumnos.add(new Alumno ("21040085","ING. CIVIL","AGUILAR VUELVAS JONADHAT",""));
        alumnos.add(new Alumno ("21040086","ING. MECATRONICA","ESTRADA BUCIO LUCIANO",""));
        alumnos.add(new Alumno ("21040087","ING. INDUSTRIAL","FERNANDEZ BECERRA JOSE DANIEL",""));
        alumnos.add(new Alumno ("21040088","ING. EN ADMINISTRACION","FUENTES MARTINEZ ALMA DELIA",""));
        alumnos.add(new Alumno ("21040089","ING. EN INDUSTRIAS ALIMENTARIAS","CAMPOS MAIZ DULCE MARIA",""));
        alumnos.add(new Alumno ("21040090","ING. CIVIL","ALBERTO ALCAZAR MANUEL",""));
        alumnos.add(new Alumno ("21040091","ING. INDUSTRIAL","FLORES CAMACHO EDWIN ALEJANDRO",""));
        alumnos.add(new Alumno ("21040092","ING. EN ADMINISTRACION","CISNEROS JIMENEZ SAMANTHA",""));
        alumnos.add(new Alumno ("21040093","ING. MECANICA","ESTRELLA ZAMBRANO ERICK YAHIR",""));
        alumnos.add(new Alumno ("21040094","ING. MECATRONICA","CASTILLO OROZCO JOSE ALBERTO",""));
        alumnos.add(new Alumno ("21040095","ING. CIVIL","CORTES VALENCIA MELINA",""));
        alumnos.add(new Alumno ("21040096","ING. EN ADMINISTRACION","DUARTE LEDESMA ANDREA",""));
        alumnos.add(new Alumno ("21040097","ING. MECATRONICA","DIAZ VAZQUEZ OCTAVIO FRANCISCO",""));
        alumnos.add(new Alumno ("21040098","ING. INDUSTRIAL","DUARTE CARRANZA VANESA",""));
        alumnos.add(new Alumno ("21040099","ING. MECATRONICA","ENG PEÑALOZA CUAUHTEMOC",""));
        alumnos.add(new Alumno ("21040100","ING. EN ADMINISTRACION","ESCALERA ROMERO ALEJANDRA MONTSERRAT",""));
        alumnos.add(new Alumno ("21040101","ING. EN SISTEMAS COMPUTACIONALES","Cortes benavides Jessica Judith",""));
        alumnos.add(new Alumno ("21040102","ING. INDUSTRIAL","FISCAL RODRIGUEZ FRANCISCO JAVIER",""));
        alumnos.add(new Alumno ("21040103","ING. EN SISTEMAS COMPUTACIONALES","BENITEZ AVILA BERTHA JATZIRY",""));
        alumnos.add(new Alumno ("21040104","ING. CIVIL","FERNANDEZ ALCAZAR GEOVANI ALEXIS",""));
        alumnos.add(new Alumno ("21040105","ING. EN ADMINISTRACION","CORNEJO GOMEZ DORA LIZBETH",""));
        alumnos.add(new Alumno ("21040106","ING. EN SISTEMAS COMPUTACIONALES","DIAZ GARCIA MIGUEL ANGEL",""));
        alumnos.add(new Alumno ("21040107","ING. ELECTRONICA","CALDERON HERRERA RICARDO ALBERTO",""));
        alumnos.add(new Alumno ("21040108","ING. CIVIL","DELGADO ORTIZ DIANA LAURA",""));
        alumnos.add(new Alumno ("21040109","ING. MECATRONICA","DIAZ RAMOS KEVIN RODRIGO",""));
        alumnos.add(new Alumno ("21040110","ING. MECANICA","DIEGO DIEGO ENRIQUE",""));
        alumnos.add(new Alumno ("21040111","ING. EN INDUSTRIAS ALIMENTARIAS","CORTES SANTIAGO MARISOL",""));
        alumnos.add(new Alumno ("21040112","ING. MECATRONICA","DIEGO GARCIA JOHANNES FRANCISCO",""));
        alumnos.add(new Alumno ("21040113","ING. EN INDUSTRIAS ALIMENTARIAS","ESCOLASTICO CAMPOS KARLA TZETZANGARI",""));
        alumnos.add(new Alumno ("21040114","ING. MECANICA","ESPINOSA CERDA VICENTE",""));
        alumnos.add(new Alumno ("21040115","ING. EN INDUSTRIAS ALIMENTARIAS","FLORES GARCIA ALEJANDRA",""));
        alumnos.add(new Alumno ("21040116","ING. EN SISTEMAS COMPUTACIONALES","GUTIERREZ CAMPOVERDE LUIS ENRIQUE",""));
        alumnos.add(new Alumno ("21040117","ING. MECATRONICA","HERNANDEZ ARELLANO JESUS ANTONIO",""));
        alumnos.add(new Alumno ("21040118","ING. EN SISTEMAS COMPUTACIONALES","GARCIA SAUCEDO CARLOS GAEL",""));
        alumnos.add(new Alumno ("21040119","ING. EN SISTEMAS COMPUTACIONALES","GALVAN NUÑEZ GAEL",""));
        alumnos.add(new Alumno ("21040120","ING. ELECTRONICA","GONZALEZ BARRERA EDGAR",""));
        alumnos.add(new Alumno ("21040121","ING. EN ADMINISTRACION","GUZMAN PIMENTEL JULIANA QUETZALY",""));
        alumnos.add(new Alumno ("21040122","ING. EN ADMINISTRACION","GARCIA ARELLANO JOSUE ULISES",""));
        alumnos.add(new Alumno ("21040123","ING. EN INDUSTRIAS ALIMENTARIAS","GONZALEZ GUERRERO ALEJANDRO",""));
        alumnos.add(new Alumno ("21040124","ING. EN ADMINISTRACION","GARCIA GOMEZ CECILIA ERANDI",""));
        alumnos.add(new Alumno ("21040125","ING. EN ADMINISTRACION","GARCIA ORTIZ NANCY DANIELA",""));
        alumnos.add(new Alumno ("21040126","ING. EN INDUSTRIAS ALIMENTARIAS","GODINEZ RIOS GUADALUPE MONSERRAT",""));
        alumnos.add(new Alumno ("21040127","ING. INDUSTRIAL","PEREZ TREJO LILIANA",""));
        alumnos.add(new Alumno ("21040128","ING. INDUSTRIAL","GARCIA TALAVERA ULISES",""));
        alumnos.add(new Alumno ("21040129","ING. EN INDUSTRIAS ALIMENTARIAS","GOMEZ JIMENEZ CAROL NAYELI",""));
        alumnos.add(new Alumno ("21040130","ING. EN SISTEMAS COMPUTACIONALES","GONZALEZ OROZCO JUAN CARLOS",""));
        alumnos.add(new Alumno ("21040131","ING. EN ADMINISTRACION","JIMENEZ VELAZUQEZ ROCIO GUADALUPE",""));
        alumnos.add(new Alumno ("21040132","ING. EN ADMINISTRACION","GOMEZ HERNANDEZ ALEXIA ASTRID",""));
        alumnos.add(new Alumno ("21040133","ING. EN SISTEMAS COMPUTACIONALES","GOMEZ CONTRERAS MAYRA YOSSELIN",""));
        alumnos.add(new Alumno ("21040134","ING. EN ADMINISTRACION","GALVEZ MARTINEZ ARLETTE ANDREA",""));
        alumnos.add(new Alumno ("21040135","ING. EN ADMINISTRACION","GOMEZ ALVEZ BRIAN",""));
        alumnos.add(new Alumno ("21040136","ING. EN SISTEMAS COMPUTACIONALES","GOMAR RIOS ESTEBAN",""));
        alumnos.add(new Alumno ("21040137","ING. EN ADMINISTRACION","GONZALEZ MAGAÑA ANA GALILEA",""));
        alumnos.add(new Alumno ("21040138","ING. EN ADMINISTRACION","GUZMAN ORTEGA MARIA MONSERRATH",""));
        alumnos.add(new Alumno ("21040139","ING. EN ADMINISTRACION","Gonzalez espinoza Rosa Maria",""));
        alumnos.add(new Alumno ("21040140","ING. EN SISTEMAS COMPUTACIONALES","LOPEZ PAREDES ALAN LEONARDO",""));
        alumnos.add(new Alumno ("21040141","ING. MECANICA","GONZALEZ NUÑEZ DIEGO FERNANDO",""));
        alumnos.add(new Alumno ("21040142","ING. EN ADMINISTRACION","GOMEZ FLORES IRERI GUADALUPE",""));
        alumnos.add(new Alumno ("21040143","ING. MECATRONICA","GALVAN ALEJO BRANDON EDUARDO",""));
        alumnos.add(new Alumno ("21040144","ING. EN SISTEMAS COMPUTACIONALES","GALVAN GAYTAN JUAN PABLO",""));
        alumnos.add(new Alumno ("21040145","ING. EN ADMINISTRACION","GOMEZ ARCE JUAN CARLOS",""));
        alumnos.add(new Alumno ("21040146","ING. EN SISTEMAS COMPUTACIONALES","GONZALEZ VILLA JUAN JOSE",""));
        alumnos.add(new Alumno ("21040147","ING. INDUSTRIAL","JUAREZ HERNANDEZ EDGAR GADIEL",""));
        alumnos.add(new Alumno ("21040148","ING. CIVIL","GUARDIAN SALTO ANAELA",""));
        alumnos.add(new Alumno ("21040149","ING. MECANICA","GUIZAR PEÑALOZA LEONARDO DE JESUS",""));
        alumnos.add(new Alumno ("21040150","ING. EN ADMINISTRACION","GAYTAN ROMERO PALOMA LIZBETH",""));
        alumnos.add(new Alumno ("21040151","ING. EN ADMINISTRACION","GARCIA SOLORIO CINTHYA VIANNEY",""));
        alumnos.add(new Alumno ("21040152","ING. INDUSTRIAL","GARCIA CONTRERAS ADRIAN ASAEL",""));
        alumnos.add(new Alumno ("21040153","ING. EN SISTEMAS COMPUTACIONALES","GUIDO ROJAS CARLOS DE JESUS",""));
        alumnos.add(new Alumno ("21040154","ING. MECATRONICA","HERNANDEZ ADRIAN DAVID",""));
        alumnos.add(new Alumno ("21040155","ING. EN ADMINISTRACION","LAGUNAS MENDOZA JESUS JAVIER",""));
        alumnos.add(new Alumno ("21040156","ING. ELECTRONICA","MORALES GALEANA NICOLAS",""));
        alumnos.add(new Alumno ("21040157","ING. MECATRONICA","GALVAN TORRES JAIR",""));
        alumnos.add(new Alumno ("21040158","ING. EN ADMINISTRACION","LEON MUJICA ALONDRA BERENICE",""));
        alumnos.add(new Alumno ("21040159","ING. ELECTRONICA","MORELOS BARAJAS ALEJANDRO",""));
        alumnos.add(new Alumno ("21040160","ING. EN INDUSTRIAS ALIMENTARIAS","GALVAN CIPRES CELIA ALEXANDRA",""));
        alumnos.add(new Alumno ("21040161","ING. EN SISTEMAS COMPUTACIONALES","LOPEZ CONTRERAS GRECIA",""));
        alumnos.add(new Alumno ("21040162","ING. EN ADMINISTRACION","MEDINA PEREZ ESTEFANIA",""));
        alumnos.add(new Alumno ("21040163","ING. MECATRONICA","HERNANDEZ ABARCA JESUS NICOLAS",""));
        alumnos.add(new Alumno ("21040164","ING. EN SISTEMAS COMPUTACIONALES","CASTRO GALVAN JUDIT ANAID",""));
        alumnos.add(new Alumno ("21040165","ING. INDUSTRIAL","HERRERA MARTINEZ MIGUEL ANTONIO",""));
        alumnos.add(new Alumno ("21040166","ING. INDUSTRIAL","LOPEZ PEÑA MACLOVIA",""));
        alumnos.add(new Alumno ("21040167","ING. MECATRONICA","JUAREZ NAVARRETE JOSE ARMANDO",""));
        alumnos.add(new Alumno ("21040168","ING. MECATRONICA","HERNANDEZ GONZALEZ EDUARDO JAIR",""));
        alumnos.add(new Alumno ("21040169","ING. CIVIL","HUCHIM PADILLA PAULO ANTONIO",""));
        alumnos.add(new Alumno ("21040170","ING. EN SISTEMAS COMPUTACIONALES","JACOBO BASTIDA DANIEL ALEJANDRO",""));
        alumnos.add(new Alumno ("21040171","ING. EN ADMINISTRACION","LICEA TORRES FATIMA AIRAM",""));
        alumnos.add(new Alumno ("21040172","ING. ELECTRONICA","HERNANDEZ MURILLO DYLAN EDUARDO",""));
        alumnos.add(new Alumno ("21040173","ING. EN ADMINISTRACION","GONZALEZ SEBASTIAN ALEXIS",""));
        alumnos.add(new Alumno ("21040174","ING. EN SISTEMAS COMPUTACIONALES","HERNANDEZ CABRERA BRIAN",""));
        alumnos.add(new Alumno ("21040175","ING. INDUSTRIAL","GARCIA MORENO DIANA JULISSA",""));
        alumnos.add(new Alumno ("21040176","ING. EN SISTEMAS COMPUTACIONALES","MORALES SANCHEZ HUGO",""));
        alumnos.add(new Alumno ("21040177","ING. EN ADMINISTRACION","MORALES CORTES KENIA SOFIA",""));
        alumnos.add(new Alumno ("21040178","ING. CIVIL","HERNANDEZ PLASCENCIA CARLOS DANIEL",""));
        alumnos.add(new Alumno ("21040179","ING. EN ADMINISTRACION","MADRIGAL GARCIA ROSA MARIA",""));
        alumnos.add(new Alumno ("21040180","ING. INDUSTRIAL","MATA VILLA KASSANDRA YUNUEN",""));
        alumnos.add(new Alumno ("21040181","ING. EN SISTEMAS COMPUTACIONALES","JIMENEZ FLORES IRVIN ALEXIS",""));
        alumnos.add(new Alumno ("21040182","ING. CIVIL","HERNANDEZ HERNANDEZ FELIPE JESUS",""));
        alumnos.add(new Alumno ("21040183","ING. INDUSTRIAL","LEON MENDOZA JULIETA",""));
        alumnos.add(new Alumno ("21040184","ING. EN SISTEMAS COMPUTACIONALES","HERNANDEZ SOLIS REBECA SARAI",""));
        alumnos.add(new Alumno ("21040185","ING. MECATRONICA","GUIDO CUEVAS ALFONSO",""));
        alumnos.add(new Alumno ("21040186","ING. ELECTRONICA","MEJIA RUEDA JESUS DAVID",""));
        alumnos.add(new Alumno ("21040187","ING. MECATRONICA","LOPEZ SANCHEZ EVER",""));
        alumnos.add(new Alumno ("21040188","ING. EN ADMINISTRACION","HERNANDEZ LOPEZ GABRIELA SARAHI",""));
        alumnos.add(new Alumno ("21040189","ING. INDUSTRIAL","GARCIA FLORES KARINA",""));
        alumnos.add(new Alumno ("21040190","ING. EN SISTEMAS COMPUTACIONALES","MACIEL ORDAZ BRANDON",""));
        alumnos.add(new Alumno ("21040191","ING. EN ADMINISTRACION","HERNANDEZ CABRERA DANIA GABRIELA",""));
        alumnos.add(new Alumno ("21040192","ING. EN SISTEMAS COMPUTACIONALES","HERRERA CALVILLO JUSTIN EDGARDO",""));
        alumnos.add(new Alumno ("21040193","ING. EN SISTEMAS COMPUTACIONALES","GUAPO ORTEGA KEVIN BRANDON",""));
        alumnos.add(new Alumno ("21040194","ING. EN SISTEMAS COMPUTACIONALES","HERRERA ROBLEDO JONATHAN ISAI",""));
        alumnos.add(new Alumno ("21040195","ING. EN INDUSTRIAS ALIMENTARIAS","LOZANO GARCIA JENNIFER",""));
        alumnos.add(new Alumno ("21040196","ING. MECANICA","LOZANO FERNANDEZ DIEGO",""));
        alumnos.add(new Alumno ("21040197","ING. EN SISTEMAS COMPUTACIONALES","LOPEZ CRUZ URIEL",""));
        alumnos.add(new Alumno ("21040198","ING. MECATRONICA","MARTINEZ CORDOBA RICARDO DE JESUS",""));
        alumnos.add(new Alumno ("21040199","ING. EN SISTEMAS COMPUTACIONALES","CORONA RIOS DIEGO OSVALDO",""));
        alumnos.add(new Alumno ("21040200","ING. CIVIL","MENDOZA MENDOZA DIEGO ALEJANDRO",""));
        alumnos.add(new Alumno ("21040201","ING. EN ADMINISTRACION","JUAREZ MARIN MEXLI VANESSA",""));
        alumnos.add(new Alumno ("21040202","ING. EN ADMINISTRACION","MENDOZA VIDALES EVA MARIA",""));
        alumnos.add(new Alumno ("21040203","ING. EN INDUSTRIAS ALIMENTARIAS","LOPEZ GOMEZ FERNANDO ROMAN",""));
        alumnos.add(new Alumno ("21040204","ING. MECANICA","MONTALVO HERNANDEZ ROGELIO EMMANUEL",""));
        alumnos.add(new Alumno ("21040205","ING. EN SISTEMAS COMPUTACIONALES","MEJIA URBINA MARIO DAEL",""));
        alumnos.add(new Alumno ("21040206","ING. EN SISTEMAS COMPUTACIONALES","HERNANDEZ CAMARENA ALAN JAVIER",""));
        alumnos.add(new Alumno ("21040207","ING. EN ADMINISTRACION","ONTIVEROS SANCHEZ FRIDA SOFIA",""));
        alumnos.add(new Alumno ("21040208","ING. MECATRONICA","MANRIQUEZ MARTINEZ PAULLETTE",""));
        alumnos.add(new Alumno ("21040209","ING. INDUSTRIAL","MARTINEZ CONTRERAS BRANDON",""));
        alumnos.add(new Alumno ("21040210","ING. EN ADMINISTRACION","HERNANDEZ GARCIA PAOLA",""));
        alumnos.add(new Alumno ("21040211","ING. EN INDUSTRIAS ALIMENTARIAS","MACIAS OVANDO YAEL ARTURO",""));
        alumnos.add(new Alumno ("21040212","ING. EN ADMINISTRACION","MAGAÑA OLIVARES OMAR GAEL",""));
        alumnos.add(new Alumno ("21040213","ING. MECATRONICA","LUCAS RIVERA DEYVID",""));
        alumnos.add(new Alumno ("21040214","ING. INDUSTRIAL","NARANJO BARRAGAN JANETH ALEJANDRAA",""));
        alumnos.add(new Alumno ("21040215","ING. MECATRONICA","MAGALLON LOPEZ YAHIR ALEXIS",""));
        alumnos.add(new Alumno ("21040216","ING. CIVIL","MORALES ALVAREZ DAVID",""));
        alumnos.add(new Alumno ("21040217","ING. EN INDUSTRIAS ALIMENTARIAS","HERNANDEZ TINAJERO ITZURI JOHANNA",""));
        alumnos.add(new Alumno ("21040218","ING. MECANICA","MENDOZA NUVIEDO BERTHA ALICIA",""));
        alumnos.add(new Alumno ("21040219","ING. MECATRONICA","ORTIZ GALVAN CAMILA",""));
        alumnos.add(new Alumno ("21040220","ING. EN SISTEMAS COMPUTACIONALES","MENDOZA ACUÑA RAFAEL EDUARDO",""));
        alumnos.add(new Alumno ("21040221","ING. CIVIL","MARTINEZ ZARCO PABLO ANGEL",""));
        alumnos.add(new Alumno ("21040222","ING. CIVIL","MARIN ZAMUDIO ULISES",""));
        alumnos.add(new Alumno ("21040223","ING. EN INDUSTRIAS ALIMENTARIAS","MARTINEZ APARICIO DULCE SILVIA",""));
        alumnos.add(new Alumno ("21040224","ING. INDUSTRIAL","MORALES TOMAS ASAF NICANOR",""));
        alumnos.add(new Alumno ("21040225","ING. CIVIL","RANGEL CALDERON LUIS FERNANDO",""));
        alumnos.add(new Alumno ("21040226","ING. EN ADMINISTRACION","ORTEGA HERNANDEZ ESCARLET VIRIDIANA",""));
        alumnos.add(new Alumno ("21040227","ING. CIVIL","NAVARRO SANCHEZ JESUS EDUARDO",""));
        alumnos.add(new Alumno ("21040228","ING. CIVIL","MORA CONTRERAS BERNARDA MILAGROS",""));
        alumnos.add(new Alumno ("21040229","ING. EN SISTEMAS COMPUTACIONALES","ORTIZ SOTO CARLOS EDUARDO",""));
        alumnos.add(new Alumno ("21040230","ING. INDUSTRIAL","MARTINEZ ALFARO LUIS ANGEL",""));
        alumnos.add(new Alumno ("21040231","ING. CIVIL","MORA CONTRERAS EMMANUEL",""));
        alumnos.add(new Alumno ("21040232","ING. MECATRONICA","OLMEDO VERA MANUEL",""));
        alumnos.add(new Alumno ("21040233","ING. INDUSTRIAL","MUÑOZ SANCHEZ DIEGO",""));
        alumnos.add(new Alumno ("21040234","ING. MECATRONICA","MARTINEZ HERNANDEZ EMILIO ENRIQUE",""));
        alumnos.add(new Alumno ("21040235","ING. EN SISTEMAS COMPUTACIONALES","NUÑEZ CORTES ERICK FERNANDO",""));
        alumnos.add(new Alumno ("21040236","ING. EN ADMINISTRACION","NARANJO ARROYO JOSE LUIS",""));
        alumnos.add(new Alumno ("21040237","ING. EN ADMINISTRACION","OSORNIO SOLORIO DIANA",""));
        alumnos.add(new Alumno ("21040238","ING. MECATRONICA","OROZCO MURILLO ALEJANDRO",""));
        alumnos.add(new Alumno ("21040239","ING. EN ADMINISTRACION","MENDOZA HUITAREO SANDRA",""));
        alumnos.add(new Alumno ("21040240","ING. EN ADMINISTRACION","MERCADO HUIPE JORDANIA AKETZALI",""));
        alumnos.add(new Alumno ("21040241","ING. EN ADMINISTRACION","NEGRETE SOLANO JEAN",""));
        alumnos.add(new Alumno ("21040242","ING. EN ADMINISTRACION","MANZO AVALOS MAYAJOHANNA",""));
        alumnos.add(new Alumno ("21040243","ING. INDUSTRIAL","MEDINA ALVARADO ALEXIA GISELLE",""));
        alumnos.add(new Alumno ("21040244","ING. EN SISTEMAS COMPUTACIONALES","MARTINEZ RIVERA VALERIA YAMILETH",""));
        alumnos.add(new Alumno ("21040245","ING. EN SISTEMAS COMPUTACIONALES","OSEGUERA TORRES PABLO",""));
        alumnos.add(new Alumno ("21040246","ING. MECANICA","NAVARRO PEREZ JESUS IVAN",""));
        alumnos.add(new Alumno ("21040247","ING. INDUSTRIAL","NARANJO FLORES BELEN",""));
        alumnos.add(new Alumno ("21040248","ING. EN ADMINISTRACION","OREGON AYALA LUIS ANGEL",""));
        alumnos.add(new Alumno ("21040249","ING. CIVIL","OROZCO PEÑALOZA MAURICIO",""));
        alumnos.add(new Alumno ("21040250","ING. EN ADMINISTRACION","NAVA ANTONIO CECILIA",""));
        alumnos.add(new Alumno ("21040251","ING. EN ADMINISTRACION","HERNANDEZ RIVERA MORELIA XCARET",""));
        alumnos.add(new Alumno ("21040252","ING. ELECTRONICA","PEÑALOZA BALTAZAR JORGE LUIS",""));
        alumnos.add(new Alumno ("21040253","ING. MECANICA","PEÑA PRIETO ARTURO",""));
        alumnos.add(new Alumno ("21040254","ING. ELECTRONICA","RODRIGUEZ HERNANDEZ MARTIN VIDAL",""));
        alumnos.add(new Alumno ("21040255","ING. EN INDUSTRIAS ALIMENTARIAS","PERALTA PEREZ IRERI GISEL",""));
        alumnos.add(new Alumno ("21040256","ING. INDUSTRIAL","PEDROZA MONTES ANGEL DANIEL",""));
        alumnos.add(new Alumno ("21040257","ING. MECATRONICA","SARABIA HERNANDEZ LUIS ENRIQUE",""));
        alumnos.add(new Alumno ("21040258","ING. INDUSTRIAL","HERNANDEZ SOTO VICTOR MANUEL",""));
        alumnos.add(new Alumno ("21040259","ING. CIVIL","ARRIAGA HERNANDEZ LAURA DENISSE",""));
        alumnos.add(new Alumno ("21040260","ING. EN ADMINISTRACION","PEREZ PIÑA ISAAC MANUEL",""));
        alumnos.add(new Alumno ("21040261","ING. EN ADMINISTRACION","PARDO HERNANDEZ VALERIA",""));
        alumnos.add(new Alumno ("21040262","ING. EN INDUSTRIAS ALIMENTARIAS","PAREDES PEDROZA WENDY ALEJANDRA",""));
        alumnos.add(new Alumno ("21040263","ING. EN ADMINISTRACION","RANGEL HERNANDEZ LESLY JULIANA",""));
        alumnos.add(new Alumno ("21040264","ING. EN SISTEMAS COMPUTACIONALES","BUCIO TELLEZ FABIAN IGNACIO",""));
        alumnos.add(new Alumno ("21040265","ING. ELECTRONICA","RICO CASARES JONATHAN EMMANUEL",""));
        alumnos.add(new Alumno ("21040266","ING. EN SISTEMAS COMPUTACIONALES","PEREZ PLANCARTE ROBERTO JESUS",""));
        alumnos.add(new Alumno ("21040267","ING. EN ADMINISTRACION","Perez mata Pedro",""));
        alumnos.add(new Alumno ("21040268","ING. EN ADMINISTRACION","PEREZ CALDERON KARELY MILAGROS",""));
        alumnos.add(new Alumno ("21040269","ING. EN INDUSTRIAS ALIMENTARIAS","QUEZADA CASTILLO DOLORES",""));
        alumnos.add(new Alumno ("21040270","ING. EN ADMINISTRACION","TORRES RUIZ YAHIR",""));
        alumnos.add(new Alumno ("21040271","ING. MECATRONICA","RANGEL BARRIGA MARIO EDUARDO",""));
        alumnos.add(new Alumno ("21040272","ING. ELECTRONICA","GONZALEZ ALVARADO JOSE DIEGO",""));
        alumnos.add(new Alumno ("21040273","ING. EN SISTEMAS COMPUTACIONALES","RODRIGUEZ SANCHEZ JULIAN",""));
        alumnos.add(new Alumno ("21040274","ING. EN SISTEMAS COMPUTACIONALES","MORALES FLORES AGUSTIN",""));
        alumnos.add(new Alumno ("21040275","ING. EN ADMINISTRACION","PEÑALOZA CABRERA BRICEYDA",""));
        alumnos.add(new Alumno ("21040276","ING. EN ADMINISTRACION","RENDON ROJAS KEVIN DIONEY",""));
        alumnos.add(new Alumno ("21040277","ING. ELECTRONICA","REYES MARTINEZ MANUEL",""));
        alumnos.add(new Alumno ("21040278","ING. INDUSTRIAL","RODRIGUEZ TREJO EIMY VANESSA",""));
        alumnos.add(new Alumno ("21040279","ING. MECANICA","MONTERO MORENO LUIS MIGUEL",""));
        alumnos.add(new Alumno ("21040280","ING. EN SISTEMAS COMPUTACIONALES","RODRIGUEZ GARCIA DANIEL",""));
        alumnos.add(new Alumno ("21040281","ING. EN SISTEMAS COMPUTACIONALES","SAUCEDO BAUTISTA RAFAEL BENJAMIN",""));
        alumnos.add(new Alumno ("21040282","ING. MECATRONICA","PADILLA GONZALEZ OSCAR",""));
        alumnos.add(new Alumno ("21040283","ING. MECANICA","AVALOS HERNANDEZ CHRISTIAN",""));
        alumnos.add(new Alumno ("21040284","ING. EN SISTEMAS COMPUTACIONALES","ZAMBRANO DURAN RUBEN ALEJANDRO",""));
        alumnos.add(new Alumno ("21040285","ING. CIVIL","RODRIGUEZ ARCHUNDIA CESAR ANTONIO",""));
        alumnos.add(new Alumno ("21040286","ING. EN ADMINISTRACION","MIRELES RODRIGUEZ JARELLY MARILIANNE",""));
        alumnos.add(new Alumno ("21040287","ING. CIVIL","PEREZ MENDEZ HECTOR MIGUEL",""));
        alumnos.add(new Alumno ("21040288","ING. CIVIL","RAMON CRUZ VALERIA",""));
        alumnos.add(new Alumno ("21040289","ING. MECATRONICA","RODRIGUEZ LEMUZ AGUSTIN",""));
        alumnos.add(new Alumno ("21040290","ING. INDUSTRIAL","RODRIGUEZ CARRILLO JENNIFER ALEJANDRA",""));
        alumnos.add(new Alumno ("21040291","ING. EN ADMINISTRACION","SAUCEDO RUIZ ALILEY",""));
        alumnos.add(new Alumno ("21040292","ING. CIVIL","PEREZ MARTINEZ ALEXIS",""));
        alumnos.add(new Alumno ("21040293","ING. EN SISTEMAS COMPUTACIONALES","REYES LANDA JATZIRI MARLENE",""));
        alumnos.add(new Alumno ("21040294","ING. CIVIL","REYES SOTO ROGELIO",""));
        alumnos.add(new Alumno ("21040295","ING. EN ADMINISTRACION","RODRIGUEZ ARREOLA JAZMIN GUADALUPE",""));
        alumnos.add(new Alumno ("21040296","ING. EN SISTEMAS COMPUTACIONALES","RAMIREZ SOLORIO JIMENA",""));
        alumnos.add(new Alumno ("21040297","ING. INDUSTRIAL","PONCE CONTRERAS ROSA",""));
        alumnos.add(new Alumno ("21040298","ING. EN ADMINISTRACION","CASTRO HERNANDEZ JOSE ARMANDO",""));
        alumnos.add(new Alumno ("21040299","ING. EN SISTEMAS COMPUTACIONALES","RIVERA TORRES GUSTAVO EDUARDO",""));
        alumnos.add(new Alumno ("21040300","ING. CIVIL","RAMIREZ ROMERO AZUL ARIEL",""));
        alumnos.add(new Alumno ("21040301","ING. CIVIL","TINOCO LARA RUBI",""));
        alumnos.add(new Alumno ("21040302","ING. EN SISTEMAS COMPUTACIONALES","ROJAS ARRIAGA PABLO ADRIAN",""));
        alumnos.add(new Alumno ("21040303","ING. CIVIL","RODRIGUEZ NAVARRO ARIDAI",""));
        alumnos.add(new Alumno ("21040304","ING. EN INDUSTRIAS ALIMENTARIAS","RAMIREZ RUEDA YOVANA LIZBETH",""));
        alumnos.add(new Alumno ("21040305","ING. EN SISTEMAS COMPUTACIONALES","SANCHEZ RODRIGUEZ JOSE MANUEL",""));
        alumnos.add(new Alumno ("21040306","ING. INDUSTRIAL","VERA PINEDA FAUSTINO",""));
        alumnos.add(new Alumno ("21040307","ING. EN SISTEMAS COMPUTACIONALES","ROQUE AGUILERA DULCE KARINA",""));
        alumnos.add(new Alumno ("21040308","ING. EN INDUSTRIAS ALIMENTARIAS","BARCENAS TRUJILLO GUADALUPE",""));
        alumnos.add(new Alumno ("21040309","ING. MECATRONICA","VILLASEÑOR PEREZ FERNANDO",""));
        alumnos.add(new Alumno ("21040310","ING. INDUSTRIAL","RUIZ SALVADOR MOISES DE JESUS",""));
        alumnos.add(new Alumno ("21040311","ING. CIVIL","RAMIREZ VEGA JORGE",""));
        alumnos.add(new Alumno ("21040312","ING. EN ADMINISTRACION","MENDOZA ALVAREZ CINTHIA YAZMIN",""));
        alumnos.add(new Alumno ("21040313","ING. MECATRONICA","VEGA RAYA IVAN",""));
        alumnos.add(new Alumno ("21040314","ING. EN INDUSTRIAS ALIMENTARIAS","VILLEGAS MORENO JOSE RAMON",""));
        alumnos.add(new Alumno ("21040315","ING. MECATRONICA","ROSAS RUIZ LUIS ALEJANDRO",""));
        alumnos.add(new Alumno ("21040316","ING. EN ADMINISTRACION","SARABIA SERENO ANGEL URIEL",""));
        alumnos.add(new Alumno ("21040317","ING. CIVIL","SANTANA RODRIGUEZ DONOVAN ARTURO",""));
        alumnos.add(new Alumno ("21040318","ING. EN ADMINISTRACION","ZIRANDA CERVANTES CARIDAD",""));
        alumnos.add(new Alumno ("21040319","ING. EN ADMINISTRACION","RODRIGUEZ MONTOYA YARELI GUADALUPE",""));
        alumnos.add(new Alumno ("21040320","ING. ELECTRONICA","SUAREZ RUIZ KARLA GUADALUPE",""));
        alumnos.add(new Alumno ("21040321","ING. MECATRONICA","ZARCO BLAS KEVIN",""));
        alumnos.add(new Alumno ("21040322","ING. MECATRONICA","ROJAS RODRIGUEZ KAYLA BRIANA",""));
        alumnos.add(new Alumno ("21040323","ING. EN SISTEMAS COMPUTACIONALES","SIERRA RAMIREZ IAN RODRIGO",""));
        alumnos.add(new Alumno ("21040324","ING. MECANICA","TORRES JURADO MELISSA",""));
        alumnos.add(new Alumno ("21040325","ING. EN ADMINISTRACION","SANTOYO CORONA BRYAN ALEJANDRO",""));
        alumnos.add(new Alumno ("21040326","ING. EN SISTEMAS COMPUTACIONALES","VALDEZ CAZAREZ MIGUEL NEIYING",""));
        alumnos.add(new Alumno ("21040327","ING. EN SISTEMAS COMPUTACIONALES","SORIANO HERNANDEZ JESUS ALEJANDRO",""));
        alumnos.add(new Alumno ("21040328","ING. EN ADMINISTRACION","VILLANUEVA MORENO BRAYAM ALEJANDRO",""));
        alumnos.add(new Alumno ("21040329","ING. EN INDUSTRIAS ALIMENTARIAS","VIRRUETA HERNANDEZ ANGEL GABRIEL",""));
        alumnos.add(new Alumno ("21040330","ING. EN ADMINISTRACION","VERDUZCO RODRIGUEZ CHRISTIAN REYNALDO",""));
        alumnos.add(new Alumno ("21040331","ING. CIVIL","SIERRA DIAZ VICTOR ALEJANDRO",""));
        alumnos.add(new Alumno ("21040332","ING. CIVIL","VAZQUEZ GIL PAOLA ESPERANZA",""));
        alumnos.add(new Alumno ("21040333","ING. EN ADMINISTRACION","SANCHEZ CERANO HECTOR HUGO",""));
        alumnos.add(new Alumno ("21040334","ING. MECANICA","VARGAS CARRANZA ALEJANDRO",""));
        alumnos.add(new Alumno ("21040335","ING. EN INDUSTRIAS ALIMENTARIAS","VIVEROS DAZA GUADALUPE MONTSERRATH",""));
        alumnos.add(new Alumno ("21040336","ING. INDUSTRIAL","TAPIA MEZA LUIS GENARO",""));
        alumnos.add(new Alumno ("21040337","ING. MECATRONICA","ZAVALA REYNOSO ADAN ALEJANDRO",""));
        alumnos.add(new Alumno ("21040338","ING. EN ADMINISTRACION","SOLANO BUSTOS HELEN",""));
        alumnos.add(new Alumno ("21040339","ING. EN SISTEMAS COMPUTACIONALES","RIVERA GONZALEZ VERONICA LIZETH",""));
        alumnos.add(new Alumno ("21040340","ING. MECATRONICA","VARGAS ZAMUDIO VICTOR ALFREDO",""));
        alumnos.add(new Alumno ("21040341","ING. EN ADMINISTRACION","TORRES CALDERON ARACELI BERENICE",""));
        alumnos.add(new Alumno ("21040342","ING. INDUSTRIAL","SANCHEZ NARANJO JUAN MANUEL",""));
        alumnos.add(new Alumno ("21040343","ING. MECATRONICA","VEGA EQUIHUA ERICK ANTONIO",""));
        alumnos.add(new Alumno ("21040344","ING. EN INDUSTRIAS ALIMENTARIAS","ZAMUDIO AMADOR CHRISTIAN EDUARDO",""));
        alumnos.add(new Alumno ("21040345","ING. ELECTRONICA","VIVEROS BOYZO PEDRO ABRAHAM",""));
        alumnos.add(new Alumno ("21040346","ING. MECATRONICA","VALERIO RIVERA ADRIAN",""));
        alumnos.add(new Alumno ("21040347","ING. EN ADMINISTRACION","MERAZ MENDOZA JOANA ZAMZARA",""));
        alumnos.add(new Alumno ("21040348","ING. MECANICA","VAZQUEZ MIER IVAN",""));
        alumnos.add(new Alumno ("21040349","ING. MECATRONICA","TORRES OREGEL JUAN MARCOS",""));
        alumnos.add(new Alumno ("21040350","ING. ELECTRONICA","MARTINEZ ESCAMILLA MAGDIEL IRAM",""));
        alumnos.add(new Alumno ("21040351","ING. CIVIL","SANCHEZ CRUZ CEYDI MARIA",""));
        alumnos.add(new Alumno ("21040352","ING. EN INDUSTRIAS ALIMENTARIAS","ZAPIEN RAMOS ANA GABRIELA",""));
        alumnos.add(new Alumno ("21040353","ING. ELECTRONICA","VEGA ANDRADE JAIRO",""));
        alumnos.add(new Alumno ("21040354","ING. ELECTRONICA","TORRES ANGELES ARLETH",""));
        alumnos.add(new Alumno ("21040355","ING. MECANICA","VACA GOMEZ MARCOS ANTONIO",""));
        alumnos.add(new Alumno ("21040356","ING. EN SISTEMAS COMPUTACIONALES","MAGALLAN ALTAMIRANO ANTONIO",""));
        alumnos.add(new Alumno ("21040357","ING. EN SISTEMAS COMPUTACIONALES","VAZQUEZ SANCHEZ JOSE ANTONIO",""));
        alumnos.add(new Alumno ("21040358","ING. CIVIL","SERRATO VALENCIA JORGE EDUARDO",""));
        alumnos.add(new Alumno ("21040359","ING. INDUSTRIAL","GARCIA TORRES JESUS FERNANDO",""));
        alumnos.add(new Alumno ("21040360","ING. EN SISTEMAS COMPUTACIONALES","VELAZQUEZ PEDRAZA DANIEL",""));
        alumnos.add(new Alumno ("21040361","ING. EN ADMINISTRACION","TALAVERA ALEMAN MARICELA",""));
        alumnos.add(new Alumno ("21040362","ING. MECATRONICA","ALEJANDRE MENDOZA JOSE LUIS",""));
        alumnos.add(new Alumno ("21040363","ING. MECATRONICA","ZUÑIGA VENEGAS ALEXIS JAVIER",""));
        alumnos.add(new Alumno ("21040364","ING. CIVIL","LOPEZ JIMENEZ RICARDO",""));
        alumnos.add(new Alumno ("21040365","ING. EN ADMINISTRACION","VIEYRA LIRA CRISTOPHER",""));
        alumnos.add(new Alumno ("21040366","ING. CIVIL","ZAVALA ADJUNTAS RAUL",""));
        alumnos.add(new Alumno ("21040367","ING. MECANICA","NEGRETE QUINTEROS CHRISTIAN SANTIAGO",""));
        alumnos.add(new Alumno ("21040368","ING. EN ADMINISTRACION","MORENO CERVANTES KARELY YURITZI",""));
        alumnos.add(new Alumno ("21040369","ING. MECANICA","VILCHIS TOLENTINO GREGORIO",""));
        alumnos.add(new Alumno ("21040370","ING. EN ADMINISTRACION","RAMIREZ RIVERA BRAULIO CESAR",""));
        alumnos.add(new Alumno ("21040371","ING. EN SISTEMAS COMPUTACIONALES","REYES RODRIGUEZ CARLOS ANTONIO",""));
        alumnos.add(new Alumno ("21040372","ING. CIVIL","REYES VILLANUEVA NADIA PATRICIA",""));
        alumnos.add(new Alumno ("21040373","ING. CIVIL","SANTOS VILLA NICOLE SAMANTHA",""));
        alumnos.add(new Alumno ("21040374","ING. CIVIL","VARGAS XHURAPE ARTURO GEOVANNI",""));
        alumnos.add(new Alumno ("21040375","ING. EN INDUSTRIAS ALIMENTARIAS","VALDEZ JUAREZ PERLA EUNICE",""));
        alumnos.add(new Alumno ("21040376","ING. CIVIL","TALANCON PEREZ ANGEL MANUEL",""));
        alumnos.add(new Alumno ("21040377","ING. INDUSTRIAL","VILLAGOMEZ PEREZ DIANA",""));
        alumnos.add(new Alumno ("21040378","ING. MECANICA","MARTINEZ TRUJILLO ZAHID EMMANUEL",""));
        alumnos.add(new Alumno ("21040379","ING. EN ADMINISTRACION","ESQUIVEL CORONA GABRIEL ALEJANDRO",""));
        alumnos.add(new Alumno ("21040380","ING. EN ADMINISTRACION","SOLIS PAHUAMBA SILVIA GRACIELA",""));
        alumnos.add(new Alumno ("21040381","ING. MECATRONICA","VILLEGAS RAMIREZ MIGUEL EDUARDO",""));
        alumnos.add(new Alumno ("21040382","ING. EN ADMINISTRACION","VARGAS MORALES PAOLA JAZMIN",""));
        alumnos.add(new Alumno ("21040383","ING. INDUSTRIAL","VILLALOBOS FIGUEROA RAFAEL",""));
        alumnos.add(new Alumno ("21040384","ING. EN SISTEMAS COMPUTACIONALES","LOAEZA CHAVEZ IVAN",""));
        alumnos.add(new Alumno ("21040385","ING. CIVIL","VLDEPEÑA SERVIN EMILIO LEJANDRO",""));
        alumnos.add(new Alumno ("21040386","ING. MECATRONICA","TORAN VAZQUEZ KAORY AZYRIS",""));
        alumnos.add(new Alumno ("21040387","ING. INDUSTRIAL","NARANJO ACOSTA NOEL IVAN",""));
        alumnos.add(new Alumno ("21040388","ING. INDUSTRIAL","ESQUIVEL JIMENEZ JESUS EDUARDO",""));
        alumnos.add(new Alumno ("21040389","ING. EN ADMINISTRACION","Jacobo Torres Brayan Francisco",""));
        alumnos.add(new Alumno ("21040390","ING. EN SISTEMAS COMPUTACIONALES","AYALA QUEZADA NOE",""));
        alumnos.add(new Alumno ("21040391","ING. EN ADMINISTRACION","CORTAZAR CISNEROS JAEL SARAI",""));
        alumnos.add(new Alumno ("21040392","ING. CIVIL","DIAZ AMBRIZ MARIA CARMEN",""));
        alumnos.add(new Alumno ("21040393","ING. MECATRONICA","FLORES HERNANDEZ FRANCISCO MANUEL",""));
        alumnos.add(new Alumno ("21040394","ING. EN INDUSTRIAS ALIMENTARIAS","PACHECO GONZALEZ LOURDES MONTSERRATH",""));
        alumnos.add(new Alumno ("21040395","ING. MECATRONICA","ACOSTA CASTRO MATEO",""));
        alumnos.add(new Alumno ("21040396","ING. EN ADMINISTRACION","GONZALEZ SALDIVAR BRANDON",""));
        alumnos.add(new Alumno ("21040397","ING. EN ADMINISTRACION","LOPEZ BENITEZ ANGIE KARINA",""));


        return alumnos;
    }
}
